require('user.options')
require('user.plugins')
require('user.keymaps')
require('user.colorscheme')
-- require('user.comment')
require('user.nvim-tree')
require('user.bufferline')
require('user.lualine')
require('user.autopairs')
require('user.treesitter')
